# Generated by Django 5.1 on 2024-08-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_remove_cartitems_total_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
