# Generated by Django 5.1 on 2024-08-10 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catogary',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='catogary_name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='catogary',
            new_name='category',
        ),
    ]
